#ifndef __PT_ASSET_TYPE__
#define __PT_ASSET_TYPE__


enum class PT_ASSET_TYPE
{
	MODEL_PTM,
	MODEL_OBJ,
	TEXTURE_GNF,
	PIPELINE,
	COUNT
};//enum class


enum ptPipelineEnum
{
	PT_PIPELINE_TDM,
	PT_PIPELINE_VVM,
	PT_PIPELINE_MMM,

	PT_PIPELINE_HUD,

	PT_PIPELINE_COUNT
};


enum ptMaterialsEnum
{
	PT_MATERIAL_BRICK,
	PT_MATERIAL_COW,
	PT_MATERIAL_COW_TEAPOT,
	PT_MATERIAL_DAN,
	PT_MATERIAL_EARTH,
	PT_MATERIAL_GRASS,
	PT_MATERIAL_OIL,
	PT_MATERIAL_SUN,
	PT_MATERIAL_TEDDY,
	PT_MATERIAL_WOOD,
	PT_MATERIAL_ASPHALT,
	PT_MATERIAL_MERCURY,
	PT_MATERIAL_MOON,
	PT_MATERIAL_PLUTO,

	PT_MATERIAL_VERT_COL_CHROME,
	PT_MATERIAL_VERT_COL_BRASS,
	PT_MATERIAL_VERT_COL_GOLD,
	PT_MATERIAL_VERT_COL_EMERALD,
	PT_MATERIAL_VERT_COL_RUBY,
	PT_MATERIAL_VERT_COL_PEARL,
	PT_MATERIAL_VERT_COL_MATTE,

	PT_MATERIAL_HUD,

	PT_MATERIAL_COUNT
};


enum ptObjectsEnum
{
	//PT_OBJECT_LAMP,
	PT_OBJECT_ARROW_FRONT,
	PT_OBJECT_ARROW_BACK,
	PT_OBJECT_ARROW_LEFT,
	PT_OBJECT_ARROW_RIGHT,

	// Solar System ---------
	PT_OBJECT_SUN,
	PT_OBJECT_MERCURY,
	PT_OBJECT_EARTH,
	PT_OBJECT_MOON,
	PT_OBJECT_PLUTO,
	PT_OBJECT_COMET,
	// END Solar System -----

	PT_OBJECT_GROUND,
	PT_OBJECT_GRASS_FLOOR,
	PT_OBJECT_FLOWER,
	PT_OBJECT_GEM,
	PT_OBJECT_BRICK_BLOCK,

	PT_OBJECT_AIRPLANE,
	PT_OBJECT_SKYSCRAPER,
	PT_OBJECT_TEAPOT,
	PT_OBJECT_VIOLIN_CASE,


	PT_OBJECT_COUNT
};//ptObjectsEnum


enum ptModelsEnum
{
	// PTM
	// NC = No_Colour
	// SC = Single_Colour
	PTM_MODEL_CUBE_PVC_NC,
	PTM_MODEL_CUBE_PVC_SC,
	PTM_MODEL_CUBE_SPLIT_NC,
	PTM_MODEL_CUBE_SPLIT_SC,

	PTM_MODEL_TETRA_PVC_NC,
	PTM_MODEL_TETRA_PVC_SC,
	PTM_MODEL_TETRA_SPLIT_NC,
	PTM_MODEL_TETRA_SPLIT_SC,

	PTM_MODEL_OCTA_PVC_NC,
	PTM_MODEL_OCTA_PVC_SC,
	PTM_MODEL_OCTA_SPLIT_NC,
	PTM_MODEL_OCTA_SPLIT_SC,

	PTM_MODEL_ICOS_PVC_NC,
	PTM_MODEL_ICOS_PVC_SC,
	PTM_MODEL_ICOS_SPLIT_NC,
	PTM_MODEL_ICOS_SPLIT_SC,

	PTM_MODEL_SPHERE,
	PTM_MODEL_TEAPOT,
	PTM_MODEL_TEDDY,
	PTM_MODEL_FLOOR,

	// OBJ
	OBJ_MODEL_AIRBOAT,
	OBJ_MODEL_AL,
	OBJ_MODEL_AL_NORMALS,
	OBJ_MODEL_CESSNA,
	OBJ_MODEL_COW,
	OBJ_MODEL_CUBE,
	OBJ_MODEL_DODECAHEDRON,
	OBJ_MODEL_GOURD,
	OBJ_MODEL_HUMANOID_QUAD,
	OBJ_MODEL_HUMANOID_TRI,
	OBJ_MODEL_ICOS,
	OBJ_MODEL_LAMP,
	OBJ_MODEL_MAGNOLIA,
	OBJ_MODEL_OCTA,
	OBJ_MODEL_SANDAL,
	OBJ_MODEL_SHUTTLE,
	OBJ_MODEL_SKYSCRAPER,
	OBJ_MODEL_SLOT_MACHINE,
	OBJ_MODEL_TEAPOT,
	OBJ_MODEL_TEDDY,
	OBJ_MODEL_TETRA,
	OBJ_MODEL_TRUMPET,
	OBJ_MODEL_VIOLIN_CASE,

	PT_MODEL_COUNT	// Total number of models
};//ptModelsEnum


enum ptTexturesEnum
{
	PT_TEXTURE_BRICK,
	PT_TEXTURE_COW,
	PT_TEXTURE_COW_TEAPOT,
	PT_TEXTURE_DAN,
	PT_TEXTURE_ASPHALT,
	PT_TEXTURE_EARTH,
	PT_TEXTURE_GRASS,
	PT_TEXTURE_MERCURY,
	PT_TEXTURE_MOON,
	PT_TEXTURE_PLUTO,
	PT_TEXTURE_OIL,
	PT_TEXTURE_SUN,
	PT_TEXTURE_TEDDY,
	PT_TEXTURE_WOOD,

	PT_TEXTURE_HUD_TEXT,

	PT_TEXTURE_COUNT
};//ptTexturesEnum

#endif // !__PT_ASSET_TYPE__
